In [1]:
import numpy as np

'''
slicing of string
msg = "Hello, How are you ?"

#startindex <= index < end_index

print(msg[7: 20] )
'''

'\nslicing of string\nmsg = "Hello, How are you ?"\n\n#startindex <= index < end_index\n\nprint(msg[7: 20] )\n'

In [2]:
print(f"list( range(5, 10) ) = { list( range(5, 10) ) }" )
print(f"list( range(15, 20) ) = { list( range(15, 20) )}")
print(f"list( range(0, 5) ) = {list( range(0, 5) )}")
print(f"list( range(20, 25) ) = {list( range(20, 25) )}")

l = [ list( range(5, 10) ), list( range(15, 20) ), list( range(0, 5) ), list( range(20, 25) )  ]

arr = np.array( l )

print()
#arr = np.array( [ [5, 6, 7, 8, 9], [15, 16, 17, 18, 19], [0, 1, 2, 3, 4],[20, 21, 22, 23, 24] ] )
print(l)
print()
print(arr)

list( range(5, 10) ) = [5, 6, 7, 8, 9]
list( range(15, 20) ) = [15, 16, 17, 18, 19]
list( range(0, 5) ) = [0, 1, 2, 3, 4]
list( range(20, 25) ) = [20, 21, 22, 23, 24]

[[5, 6, 7, 8, 9], [15, 16, 17, 18, 19], [0, 1, 2, 3, 4], [20, 21, 22, 23, 24]]

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [20 21 22 23 24]]


In [3]:
print( arr.shape )
print( arr )

(4, 5)
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [20 21 22 23 24]]


In [4]:
'''
Slicing of 2 dimensional Arrays
Syntax :- 
    Numpyarrayname[ row1 : row2, col1 : col2]   #row1 & col1 are inclusive whereas row2 & col2 are exclusive.
'''
#When we don't mention any row and column
arrslice = arr[ : :  ]
print("arrslice when No Row and No Column :- ")
print(arrslice)
print()

arrslice when No Row and No Column :- 
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [20 21 22 23 24]]



In [5]:
#When we mention only row2 and no columns
arrslice = arr[  : 2 , :  ]                         #If don't mention Anything in starting then, it will consider index from 0
print("arrslice only row2 and no columns :- ")
print(arrslice)
print()

arrslice only row2 and no columns :- 
[[ 5  6  7  8  9]
 [15 16 17 18 19]]



In [6]:
#When we mention only row1 and no columns
arrslice = arr[ 2 :  , :  ]             #If don't mention Anything in last then, it will consider index from row1 to last row
print("arrslice only row1 and no columns :- ")
print(arrslice)
print()

arrslice only row1 and no columns :- 
[[ 0  1  2  3  4]
 [20 21 22 23 24]]



In [7]:
#When we mention only rows and no columns
arrslice = arr[ 1 : 3 , :  ]             #If mention rows and no columns
print("arrslice only rows :- ")
print(arrslice)
print()

arrslice only rows :- 
[[15 16 17 18 19]
 [ 0  1  2  3  4]]



In [8]:
#When we mention only col2 and no rows
arrslice = arr[  :  , : 2 ]                         #If don't mention Anything in starting then, it will consider index from 0
print("arrslice only col2 and no rows :- ")
print(arrslice)
print()

arrslice only col2 and no rows :- 
[[ 5  6]
 [15 16]
 [ 0  1]
 [20 21]]



In [9]:
#When we mention only col1 and no rows
arrslice = arr[  :  , 2 :  ]            #If don't mention Anything in last then, it will consider index till last columns
print("arrslice only col1 and no rows :- ")
print(arrslice)
print()

arrslice only col1 and no rows :- 
[[ 7  8  9]
 [17 18 19]
 [ 2  3  4]
 [22 23 24]]



In [10]:
#When we mention only columns and no rows
arrslice = arr[  :  , 2 : 4 ]             #If mention columns and no rows
print("arrslice only columns and no rows :- ")
print(arrslice)
print()

arrslice only columns and no rows :- 
[[ 7  8]
 [17 18]
 [ 2  3]
 [22 23]]



In [12]:
#When we mention both rows and columns
arrslice = arr[ 1 : 4 , 2 : 4 ]     #If mention both then, it will consider index (from row1 to row2) and (from col1 to col2 )
print( arr )
print("arrslice both rows and columns :- ")
print(arrslice)
print()

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [20 21 22 23 24]]
arrslice both rows and columns :- 
[[17 18]
 [ 2  3]
 [22 23]]



In [15]:
x = np.array( range( 1, 13) )
print( x )

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
print( x )
print()
print( np.split( x, [3, 5, 8] ) )

'''
It will run slcing into parts means,

[ 3, 5, 8 ] = :3 and 3:5 and 5:8 and 8:
'''

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8]), array([ 9, 10, 11, 12])]


'\nIt will run slcing into parts means,\n\n[ 3, 5, 8 ] = :3 and 3:5 and 5:8 and 8:\n'

In [20]:
print( np.array( range( 0, 16 ) ) )
print( np.arange(16) )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [25]:
print( np.arange( 16 ).reshape( ( 1, 16 ) ) )
print()
print( np.arange( 16 ).reshape( ( 2, 8 ) ) )
print()
print( np.arange( 16 ).reshape( ( 8, 2 ) ) )
print()
print( np.arange( 16 ).reshape( ( 2, 2, 4 ) ) )
print()
print( np.arange( 16 ).reshape( ( 2, 2, 2, 2 ) ) )
print()
print( np.arange( 16 ).reshape( ( 1, 16 ) ) )
print()
grid = np.arange(16).reshape( (4, 4) )
grid

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
np.vsplit(grid, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [27]:
for i in np.vsplit(grid, [2]):
    print( i )
    print()

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]



In [28]:
np.vsplit(grid, [2, 3])        #It is spliting grid array vertically by following split() rule also.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

In [29]:
for i in np.vsplit(grid, [2, 3]):
    print( i )
    print()

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]]

[[12 13 14 15]]



In [30]:
print( grid )
print()
np.hsplit(grid, [2])                # : 2 and 2 :

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [31]:
np.hsplit(grid, [2, 3])                # : 2,  2 : 3 and 3 :

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]