In [1]:
'''Things going to be covered, 
1) full   -> To fill Custom value of any data type.
2) ones   -> To fill 1. value
3) zeros   -> To fill 0. value
4) eye   -> Identity Matrix
5) random.random  -> To fill random values/ numbers from 0 to 1
'''

'Things going to be covered, \n1) full   -> To fill Custom value of any data type.\n2) ones   -> To fill 1. value\n3) zeros   -> To fill 0. value\n4) eye   -> Identity Matrix\n5) random.random  -> To fill random values/ numbers from 0 to 1\n'

In [2]:
import numpy as np

In [6]:
#fill - To fill the array with same elements( Ex :- fill the array elements as 7 everywhere in array )
arr7 = np.full( (3, 4 ), 8 )
print( arr7 )

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [7]:
#fill - To fill the array with same elements( Ex :- fill the array elements as 7.6 everywhere in array )
arr7point6 = np.full( (2, 4), 7.6 )
print( arr7point6 )
print()
arrone = np.full( (2, 4), 'Hi' )
print(arrone)

[[7.6 7.6 7.6 7.6]
 [7.6 7.6 7.6 7.6]]

[['Hi' 'Hi' 'Hi' 'Hi']
 ['Hi' 'Hi' 'Hi' 'Hi']]


In [8]:
#zeros - To fill the array with 0( Ex :- fill the array elements as 0 everywhere in array )
arr0 = np.zeros( (2, 4) )
print( arr0 )
print()
arr0 = np.full( (2, 4), 0. )
print( arr0 )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#ones - To fill the array with 1( Ex :- fill the array elements as 1 everywhere in array )
arr1 = np.ones( (2, 4) )
print( arr1 )
print()
arr1 = np.full( (2, 4), 1. )
print( arr1 )

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#eye - To fill the array with digonal as 1( Ex :- fill the array elements digonally as 1 and others as 0 in array )
arreye = np.eye( 3, 3 )    #Only Single '()' bracket. No double bracket like fill, zeros and ones
print( arreye )

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#random.random - To fill the array with random number form 0 to 1
arrrandom = np.random.random( (2, 4) )
print( arrrandom )
print()
#?np.random.randint
n1 = np.random.randint( 2, 10, 4 )
n2 = np.random.randint( 12, 20, 4 )
#n3 = np.random.randint( 22, 30, 6 )
print( n1 )
print( n2 )
#print( n3 )

[[0.06816092 0.8723568  0.74908136 0.94257873]
 [0.65228713 0.25419337 0.79321609 0.62530151]]

[2 7 8 5]
[16 19 15 12]


In [14]:
n1 = list(n1 )
n2 = list( n2 )
#n3 = list( n3 )

In [15]:
l = []
l.append( n1 )
l.append( n2 )
#l.append( n3 )
print( l )

[[2, 7, 8, 5], [16, 19, 15, 12]]


In [16]:
l = np.array( l )
print( l )

[[ 2  7  8  5]
 [16 19 15 12]]
